W.AppWeb/Models/ErrorViewModel.cs
namespace W.AppWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

W.AppWeb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using W.AppWeb.Models;

namespace W.AppWeb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

W.AppWeb/Controllers/PersonaWController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using System.Threading.Tasks;
using W.BL;
using W.EN;
using W.DAL;

namespace W.AppWeb.Controllers
{
    public class PersonaWController : Controller
    {
        private readonly PersonaWBL _personawBL;
        public PersonaWController(PersonaWBL pPersonaWBl)
        {
            _personawBL = pPersonaWBl;
        }
        // GET: PersonaWController
        public async Task<ActionResult> Index()
        {
            var personasw = await _personawBL.ObtenerTodosAsync();
            return View(personasw);
        }

        // GET: PersonaWController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: PersonaWController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PersonaWController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PersonaW pPersonaW)
        {
            try
            {
                await _personawBL.CrearAsync(pPersonaW);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PersonaWController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var personaw = await _personawBL.ObtenerPorIdAsync(new PersonaW { Id = id });
            return View(personaw);
        }

        // POST: PersonaWController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PersonaW pPersonaW)
        {
            try
            {
                await _personawBL.ModificarAsync(pPersonaW);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PersonaWController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var personaw = await _personawBL.ObtenerPorIdAsync(new PersonaW { Id = id });
            return View(personaw);
        }

        // POST: PersonaWController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(PersonaW pPersonaW)
        {
            try
            {
                await _personawBL.EliminarAsync(new PersonaW { Id = pPersonaW.Id });
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        //aqui 
        [HttpGet]
        public async Task<ActionResult> Index(string nombre, string apellido)
        {
            // Si no hay parámetros de búsqueda, mostrar todos
            if (string.IsNullOrEmpty(nombre) && string.IsNullOrEmpty(apellido))
            {
                var todos = await _personawBL.ObtenerTodosAsync();
                return View(todos);
            }

            // Búsqueda filtrada
            var resultados = await _personawBL.BuscarPorNombreApellidoAsync(nombre, apellido);
            return View(resultados);
        }
    }
}

W.AppWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

W.AppWeb/Views/PersonaW/Create.cshtml
@using W.EN
@model PersonaW;
<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Persona</h5>
    </div>
    <div class="card-body">
        <form asp-action="Create" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="NombreW" class="form-label"></label>
                <input asp-for="NombreW" class="form-control" />
                <span asp-validation-for="NombreW" class="text-danger"></span>

                <label asp-for="ApellidoW" class="form-label"></label>
                <input asp-for="ApellidoW" class="form-control" />
                <span asp-validation-for="ApellidoW" class="text-danger"></span>

                <label asp-for="FechaNacimientoW" class="form-label"></label>
                <input asp-for="FechaNacimientoW" class="form-control" />
                <span asp-validation-for="FechaNacimientoW" class="text-danger"></span>

                <label asp-for="SueldoW" class="form-label"></label>
                <input asp-for="SueldoW" class="form-control" />
                <span asp-validation-for="SueldoW" class="text-danger"></span>

                <label asp-for="EstatusW" class="form-label"></label>
                <input asp-for="EstatusW" class="form-control" />
                <span asp-validation-for="EstatusW" class="text-danger"></span>

                <label asp-for="ComentarioW" class="form-label"></label>
                <input asp-for="ComentarioW" class="form-control" />
                <span asp-validation-for="ComentarioW" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success">Guardar</button>
        </form>
    </div>
</div>

W.AppWeb/Views/PersonaW/Delete.cshtml
@using W.EN
@model PersonaW;
<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Seguro que desea Eliminar la Persona ?</h5>
    </div>
    <div class="card-body">
        <form asp-action="Delete" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="NombreW" class="form-label"></label>
                <input asp-for="NombreW" class="form-control" />
                <span asp-validation-for="NombreW" class="text-danger"></span>

                <label asp-for="ApellidoW" class="form-label"></label>
                <input asp-for="ApellidoW" class="form-control" />
                <span asp-validation-for="ApellidoW" class="text-danger"></span>

                <label asp-for="FechaNacimientoW" class="form-label"></label>
                <input asp-for="FechaNacimientoW" class="form-control" />
                <span asp-validation-for="FechaNacimientoW" class="text-danger"></span>

                <label asp-for="SueldoW" class="form-label"></label>
                <input asp-for="SueldoW" class="form-control" />
                <span asp-validation-for="SueldoW" class="text-danger"></span>

                <label asp-for="EstatusW" class="form-label"></label>
                <input asp-for="EstatusW" class="form-control" />
                <span asp-validation-for="EstatusW" class="text-danger"></span>

                <label asp-for="ComentarioW" class="form-label"></label>
                <input asp-for="ComentarioW" class="form-control" />
                <span asp-validation-for="ComentarioW" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success">Eliminar</button>
        </form>
    </div>
</div>

W.AppWeb/Views/PersonaW/Edit.cshtml
@using W.EN
@model PersonaW;
<div class="card">
    <div class="card-header bg-primary text-white">
        <h5>Persona</h5>
    </div>
    <div class="card-body">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="mb-3">
                <label asp-for="NombreW" class="form-label"></label>
                <input asp-for="NombreW" class="form-control" />
                <span asp-validation-for="NombreW" class="text-danger"></span>

                <label asp-for="ApellidoW" class="form-label"></label>
                <input asp-for="ApellidoW" class="form-control" />
                <span asp-validation-for="ApellidoW" class="text-danger"></span>

                <label asp-for="FechaNacimientoW" class="form-label"></label>
                <input asp-for="FechaNacimientoW" class="form-control" />
                <span asp-validation-for="FechaNacimientoW" class="text-danger"></span>

                <label asp-for="SueldoW" class="form-label"></label>
                <input asp-for="SueldoW" class="form-control" />
                <span asp-validation-for="SueldoW" class="text-danger"></span>

                <label asp-for="EstatusW" class="form-label"></label>
                <input asp-for="EstatusW" class="form-control" />
                <span asp-validation-for="EstatusW" class="text-danger"></span>

                <label asp-for="ComentarioW" class="form-label"></label>
                <input asp-for="ComentarioW" class="form-control" />
                <span asp-validation-for="ComentarioW" class="text-danger"></span>
            </div>
            <button type="submit" class="btn btn-success">Modificar</button>
        </form>
    </div>
</div>

W.AppWeb/Views/PersonaW/Index.cshtml
@using W.EN

@model List<PersonaW>
<h1>Lista de Personas</h1>

<!--Busqueda por nombre-->
<form asp-action="Index" method="get" class="mb-4">
    <div class="row">
        <div class="col-md-5">
            <label class="control-label">Nombre:</label>
            <input type="text" name="nombre" class="form-control"
                   value="@Context.Request.Query["nombre"]"
                   placeholder="Buscar por nombre" />
        </div>
        <!--Busqueda por apellido-->
        <div class="col-md-5">
            <label class="control-label">Apellido:</label>
            <input type="text" name="apellido" class="form-control"
                   value="@Context.Request.Query["apellido"]"
                   placeholder="Buscar por apellido" />
        </div>
        <div class="col-md-2 d-flex align-items-end">

            <button type="submit" class="btn btn-primary mr-2">Buscar</button>
            <!--Limpiar busqueda-->
            <a asp-action="Index" class="btn btn-outline-secondary">Limpiar</a>
        </div>
    </div>
</form>

<div>
    <a asp-controller="PersonaW" asp-action="Create" class="btn btn-primary">Nuevo</a>
    <br />
    <br />
    @if (Model != null)
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <td>Nombre</td>
                    <td>Apellido</td>
                    <td>Fecha Nacimiento</td>
                    <td>Sueldo</td>
                    <td>Estatus</td>
                    <td>Comentarios</td>
                    <td>Acciones</td>
                </tr>
            </thead>
            <tbody>
                @foreach (var personaw in Model)
                {
                    <tr>
                        <th>@personaw.NombreW</th>
                        <th>@personaw.ApellidoW</th>
                        <th>@personaw.FechaNacimientoW</th>
                        <th>@personaw.SueldoW</th>
                        <th>@personaw.EstatusW</th>
                        <th>@personaw.ComentarioW</th>

                        <th>
                            <a class="btn btn-primary" asp-controller="PersonaW" asp-action="Edit" asp-route-id="@personaw.Id">Editar</a>|
                            <a class="btn btn-danger" asp-controller="PersonaW" asp-action="Delete" asp-route-id="@personaw.Id">Eliminar</a>
                        </th>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <div class="alert alert-warning mt-3">No se encontraron personas con los criterios de búsqueda</div>
    }

</div>

W.AppWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - W.AppWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/W.AppWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">W.AppWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PersonaW" asp-action="Index">Personas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - W.AppWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>